### PR TITLE
Did what was told to!

### PR DESCRIPTION
**Pull request by anubhav666**
You're free to make edits🙇‍♂️

### CODE REVIEW

**Comment by singhayushh** [comment]
The college name getting erased out isn't a good thing 😐

**Comment by anubhav666** [comment]
What else do you suggest?😥

**Comment by singhayushh** [comment]
When that typing effect gets totally completed for the college name, that area can be made blank for some seconds and then some phrase like Learn, Grow, Build can take it's place. 

I'm just suggesting, the college name getting erased shouldn't be there :thinking:

**Comment by anubhav666** [comment]
ok will try!

**Pull request closed without merging**
