### PR TITLE
Increased font size and added funky theme button images

### PR DESCRIPTION
**Pull request by akm15machine**
Oh, ..and changed the radius and width of the nav icons

### CODE REVIEW

**Comment by akm15machine** [comment]
Changed the DSC dark theme logo

**Review by singhayushh — APPROVED** [review]
Not sure if 18px font-size would fit perfect though 😅

**Comment by akm15machine** [comment]
> Not sure if 18px font-size would fit perfect though 😅

Here, have a look at the 18px font size:
image
image

**Comment by singhayushh** [comment]
Thanks!
It looks good 🚀

**Pull request merged**
